management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,circuitbreakers,retries
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

spring:
  cloud:
    loadbalancer:
      cache:
        ttl: 5s
    openfeign:
      micrometer:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic

eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.supermarket: INFO
