CREATE TABLE IF NOT EXISTS stock_transfers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_branch_id BIGINT NOT NULL,
    source_branch_name VARCHAR(100),
    target_branch_id BIGINT NOT NULL,
    target_branch_name VARCHAR(100),
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100),
    quantity INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_by_id BIGINT NOT NULL,
    requested_by_username VARCHAR(50),
    approved_by_id BIGINT,
    approved_by_username VARCHAR(50),
    requested_at DATETIME NOT NULL,
    approved_at DATETIME,
    completed_at DATETIME,
    rejection_reason VARCHAR(255),
    completion_attempt INT NOT NULL DEFAULT 0,
    completion_state VARCHAR(20) NOT NULL DEFAULT 'NONE',
    version BIGINT,
    INDEX idx_transfers_source (source_branch_id),
    INDEX idx_transfers_target (target_branch_id),
    INDEX idx_transfers_requested_by (requested_by_id)
);
