CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS catalogdb;
CREATE DATABASE IF NOT EXISTS branchdb;
CREATE DATABASE IF NOT EXISTS salesdb;
CREATE DATABASE IF NOT EXISTS transferdb;
CREATE DATABASE IF NOT EXISTS notificationdb;
CREATE DATABASE IF NOT EXISTS auditdb;
